# Generated by Django 5.0 on 2023-12-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_question_correct_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice_a',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice_b',
            new_name='possible_answer_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice_c',
            new_name='possible_answer_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice_d',
            new_name='possible_answer_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='correct_choice',
            new_name='possible_answer_4',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='gg'),
            preserve_default=False,
        ),
    ]
